### PR TITLE
Update icons and add instructions on how to do this

### PR DESCRIPTION
**Pull request by nazar-pc**
Had to fix scripts a bit to make them work again.

Couldn't update GNOME's icons due to https://gitlab.gnome.org/Teams/Design/icon-development-kit/-/issues/126

Resolves https://github.com/Relm4/icons/issues/23

### CODE REVIEW

**Comment by AaronErhardt** [comment]
I apologize for the lack of documentation regarding this, but I converted the icons from icon-dev-kit with [Symbolic Preview](https://flathub.org/apps/org.gnome.design.SymbolicPreview) so far, which does not rely on a script. That said, a script would be more convenient.

**Comment by nazar-pc** [comment]
Well, in that case the commented-out code will not be helpful anyway, so this PR is still valid. If you can push here or separately updates to `icon-development-kit` too that'd be fantastic.

BTW what about stable release for this after that?

**Comment by nazar-pc** [comment]
> We should probably make this optional instead of commenting it out and document where to export the icons with SymbolicPreview.

This is exactly what was confusing to me. If it is not there, why not uploading icons to the target directory right away?

**Comment by AaronErhardt** [comment]
> This is exactly what was confusing to me. If it is not there, why not uploading icons to the target directory right away?

There is still the `analyze_dir` function that goes into the subdirectories and extracts all the icons from there. Plus it renames the icons if there happen to be duplicates during this "flatten" operation. So it's more convenient to automate at least this part instead of extracting the icons in the file manager.

**Comment by nazar-pc** [comment]
Okay, restored it with a warning if missing

**Review by AaronErhardt — APPROVED** [review]
Thanks for your patience, everything looks good now.

**Comment by nazar-pc** [comment]
Will you update it or should I do it?

**Comment by AaronErhardt** [comment]
I assume it would just be about changing the branch of the submodule. I can do that, but if you want to have this done right away and not in a couple of days, it'll be faster if you do it probably.

**Pull request merged**
