### PR TITLE
Update `icon-development-kit`

### PR DESCRIPTION
**Pull request by nazar-pc**
Follow-up to https://github.com/Relm4/icons/pull/26 that updates icons from `icon-development-kit` and corrects instructions accordingly

### CODE REVIEW

**Review by AaronErhardt — APPROVED** [review]
That's truly a nice solution to the problem! Thanks for digging into this issue and solving it!

Btw. the amount of changed files almost made Firefox crash while reviewing the PR :sweat_smile:

**Comment by nazar-pc** [comment]
I should have separated icons into a separate commit, but was too lazy for that

**Comment by nazar-pc** [comment]
Could you push another beta release so I don't have to pull git version on my end, please?

**Comment by AaronErhardt** [comment]
Done

**Pull request merged**
